global:
  nameOverride: m3-music
  fullnameOverride: ""
  serviceAccount:
    name: ""

frontend:
  replicaCount: 1

  image:
    repository: YOUR_ECR_FRONTEND
    tag: latest
    pullPolicy: Always

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: m3music.local
        paths:
          - path: /
            pathType: Prefix
    tls: []

backend:
  replicaCount: 1
  image:
    repository: YOUR_ECR_BACKEND
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 10000

env:
  PORT: "10000"
  FRONTEND_URL: ""
  AWS_REGION: ""
  S3_BUCKET_NAME: ""
  S3_PUBLIC_URL: ""
  GOOGLE_DRIVE_FOLDER_ID: ""
  GOOGLE_SERVICE_ACCOUNT_EMAIL: ""

secretEnv:
  MONGODB_URI: ""
  JWT_SECRET: ""

serviceAccount:
  create: true
  annotations: {}
  automount: true

autoscaling:
  enabled: false
