replicaCount: 1

image:
  repository: m3music-frontend
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 80

resources: {}

livenessProbe:
  httpGet:
    path: /
    port: 80

readinessProbe:
  httpGet:
    path: /
    port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: m3music.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

imagePullSecrets: []

autoscaling:
  enabled: false

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  create: true
  name: ""
