apiVersion: v1
kind: Secret
metadata:
  name: {{ include "m3music.secretName" . }}
  labels:
    {{- include "m3music.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGODB_URI: {{ .Values.secretEnv.MONGODB_URI | quote }}
  JWT_SECRET: {{ .Values.secretEnv.JWT_SECRET | quote }}

