apiVersion: v1
kind: Secret
metadata:
  name: {{ include "m3music.fullname" . }}-secrets
  labels:
    {{- include "m3music.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGODB_URI: {{ .Values.secretEnv.MONGODB_URI | quote }}
  JWT_SECRET: {{ .Values.secretEnv.JWT_SECRET | quote }}
  GOOGLE_PRIVATE_KEY: {{ .Values.secretEnv.GOOGLE_PRIVATE_KEY | quote }}

