replicaCount: 1

image:
  repository: m3music-backend
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 10000

resources: {}

livenessProbe:
  httpGet:
    path: /health
    port: 10000

readinessProbe:
  httpGet:
    path: /health
    port: 10000

imagePullSecrets: []

autoscaling:
  enabled: false

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  create: true
  name: ""
